# ロボットの前後タイヤ間の距離
wheelbase: 0.252 # メートル

max_speed:          0.2   # m/s
max_steering_angle: 0.8  #ラジアン

update_pose_rate: 0.02

# Lidar simulation parameters
scan_beams: 360
scan_field_of_view: 6.28 # radians

# base_linkは後輪軸の中心, LiDARは前輪軸の中心であるため, wheelbaseと等しい
scan_distance_to_base_link: 0.252 # meters

# The standard deviation of the noise applied
# to the lidar simulation
scan_std_dev: 0.001 # meters

# The probability threshold for points
# in the occupancy grid to be considered "free".
# Used for the lidar simulator.
map_free_threshold: 0.3

# Enables joystick if true
joy: true
joy_speed_axis: 1
joy_angle_axis: 2
joy_max_speed: 2. # meters/second

# The names of topics to listen and publish to
joy_topic: "/joy"
drive_topic: "/drive"
map_topic: "/map"
distance_transform_topic: "/dt"
scan_topic: "/scan"
pose_topic: "/pose"
odom_topic: "/odom"
cmd_vel:    "/cmd_vel"
pose_rviz_topic: "/initialpose"

# The names of the transformation frames published to
map_frame:  "map"
base_frame: "base_link"
#base_frame: "base_footprint"
scan_frame: "laser"
odom_frame: "odom"
scanmatcher_frame: "scanmatcher_frame"

# Turn this off for mapping
broadcast_transform: true
