# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sp(object):
    def setupUi(self, sp):
        sp.setObjectName("sp")
        sp.resize(1163, 654)
        sp.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.pushButton_6 = QtWidgets.QPushButton(sp)
        self.pushButton_6.setGeometry(QtCore.QRect(650, 520, 89, 41))
        self.pushButton_6.setStyleSheet("color: rgb(239, 41, 41);\n"
"background-color: rgb(46, 52, 54);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox = QtWidgets.QGroupBox(sp)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(40, 30, 711, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.groupBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(610, 90, 89, 31))
        self.pushButton_7.setStyleSheet("color: rgb(239, 41, 41);\n"
"background-color: rgb(46, 52, 54);")
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(90, 60, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(sp)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 180, 711, 161))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 60, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setDefault(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 60, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setDefault(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(430, 60, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(580, 110, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_3 = QtWidgets.QGroupBox(sp)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 390, 711, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"")
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 60, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setDefault(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(sp)
        self.label.setGeometry(QtCore.QRect(840, 70, 251, 251))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../catkin_actt_pc/src/actt_pc/maps/stata_basement.png"))
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(sp)
        self.graphicsView.setGeometry(QtCore.QRect(820, 430, 256, 192))
        self.graphicsView.setInteractive(True)
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(sp)
        self.pushButton.clicked.connect(sp.ssh_client)
        self.pushButton_6.clicked.connect(sp.stop)
        self.pushButton_2.clicked.connect(sp.save_map)
        self.pushButton_3.clicked.connect(sp.mapping)
        self.pushButton_7.clicked.connect(sp.ssh_dis)
        self.pushButton_5.clicked.connect(sp.load_map)
        self.pushButton_4.clicked.connect(sp.navigation)
        self.pushButton_8.clicked.connect(sp.fin_mapping)
        QtCore.QMetaObject.connectSlotsByName(sp)

    def retranslateUi(self, sp):
        _translate = QtCore.QCoreApplication.translate
        sp.setWindowTitle(_translate("sp", "Autonomous"))
        self.pushButton_6.setText(_translate("sp", "All stops"))
        self.groupBox.setTitle(_translate("sp", "SETUP"))
        self.pushButton_7.setText(_translate("sp", "Disconnet"))
        self.pushButton.setText(_translate("sp", "Wake up ACTT"))
        self.groupBox_2.setTitle(_translate("sp", "MAPPING"))
        self.pushButton_3.setText(_translate("sp", "Running SLAM"))
        self.pushButton_2.setText(_translate("sp", "Save a map"))
        self.pushButton_5.setText(_translate("sp", "Load a map"))
        self.pushButton_8.setText(_translate("sp", "Finish"))
        self.groupBox_3.setTitle(_translate("sp", "NAVIGATION STACK"))
        self.pushButton_4.setText(_translate("sp", "Running Navigation Stack"))

